apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: mylandmarktech/nodejs-fe-app
      ports:
      - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:  
  name: webappsvc
spec:
  selector:    
    app: webapp
  type: NodePort
  ports:  
  - targetPort: 9981
    port: 80
    nodePort: 31000
  
